[project]
name = "myproj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.117.1",
    "python-lsp-server[all]>=1.13.1",
    "requests>=2.32.5",
    "websockets>=15.0.1",
]
